### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ivanchen52** [banyh/PyStanfordNLP#1]
您好,
我在試著使用您的工具時,程式有報錯,以下是錯誤訊息
File "C:\Program Files\Anaconda3\lib\site-packages\stanford_segmenter\java.py", line 44, in __init__
    self.dicset = pickle.load(f)
ImportError: No module named '__builtin__\r'

我用的是python 3.5
請問我應該要怎麼做才能順利執行,謝謝.

**Comment by banyh** [comment]
你先單獨把 https://github.com/banyh/PyStanfordNLP/blob/master/stanford_segmenter/dict.set 下載下來，然後執行下面的指令，看結果是否一樣：
```python
import pickle
with open('dict.set', 'rb') as f:
    dicset = pickle.load(f)
```

我用 Python 3.5 on Window 10 讀取是沒問題的。

**Comment by ivanchen52** [comment]
讀取測試成功了,謝謝.
